# Puerto del servidor
server.port=8080

#aceptar otra conexion que no sea de la misma maquina
server.address=0.0.0.0
# Tamano maximo de archivo subido (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Nombre de la app
spring.application.name=pkm-api
