// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexerPKM.flex

/*
 * PKM_FORMS - Analizador Lexico para archivos .pkm
 * Los emojis @[...] se resuelven a Unicode directamente en el lexer.
 */
package com.example.pkmforms.analyzer.pkm;
import java_cup.runtime.*;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class LexerPKM implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int META = 2;
  public static final int CADENA_STATE = 4;
  public static final int EMOJI_STATE = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\1\22\0\1\4\1\0"+
    "\1\5\1\6\4\0\1\7\1\10\2\0\1\11\1\12"+
    "\1\13\1\14\12\15\2\0\1\16\1\17\1\20\1\0"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\0\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\0\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\0\1\53\1\0\1\54"+
    "\1\0\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\0\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\0\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\55\1\0\1\56\7\0\1\3"+
    "\252\0\2\32\115\0\1\42\u01a8\0\2\3\u0100\0\1\33"+
    "\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\2\1\1\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\1\1\7\15\1\1\10\1\11\2\1\1\12\1\13"+
    "\1\12\1\14\3\0\1\15\35\0\1\16\1\17\2\0"+
    "\1\6\41\0\1\20\1\0\1\21\3\0\1\22\35\0"+
    "\1\23\6\0\1\24\1\25\42\0\1\26\4\0\1\27"+
    "\4\0\1\30\23\0\1\31\2\0\1\32\1\0\1\33"+
    "\5\0\1\34\1\0\1\35\1\36\1\0\1\37\2\0"+
    "\1\40\1\41\1\0\1\42\1\0\1\43\1\0\1\44"+
    "\4\0\1\45\2\0\1\46\6\0\1\47\1\50\1\0"+
    "\1\51\10\0\1\52\1\53\1\0\1\54\5\0\1\55"+
    "\3\0\1\56\4\0\1\57\1\0\1\60\1\61\2\0"+
    "\1\62\3\0\1\63\1\64\1\0\1\65\2\0\1\66"+
    "\1\0\1\67\1\70\1\71\2\0\1\72\3\0\1\73"+
    "\4\0\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[320];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\274\0\u011a"+
    "\0\u0149\0\274\0\274\0\u0178\0\u01a7\0\u01d6\0\274\0\u0205"+
    "\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d"+
    "\0\u03ac\0\u03db\0\u040a\0\u0439\0\274\0\274\0\u0468\0\u0497"+
    "\0\u04c6\0\274\0\u04f5\0\274\0\u0524\0\u0553\0\u0582\0\274"+
    "\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872"+
    "\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea"+
    "\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\274\0\274\0\u0b04"+
    "\0\u0b33\0\u05b1\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d"+
    "\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5"+
    "\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d"+
    "\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5"+
    "\0\u10e4\0\u1113\0\u1142\0\274\0\u1171\0\274\0\u11a0\0\u11cf"+
    "\0\u11fe\0\274\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318"+
    "\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403\0\u1432\0\u1461\0\u1490"+
    "\0\u14bf\0\u14ee\0\u151d\0\u154c\0\u157b\0\u15aa\0\u15d9\0\u1608"+
    "\0\u1637\0\u1666\0\u1695\0\u16c4\0\u16f3\0\u1722\0\u1751\0\274"+
    "\0\u1780\0\u17af\0\u17de\0\u180d\0\u183c\0\u186b\0\274\0\274"+
    "\0\u189a\0\u18c9\0\u18f8\0\u1927\0\u1956\0\u1985\0\u19b4\0\u19e3"+
    "\0\u1a12\0\u1a41\0\u1a70\0\u1a9f\0\u1ace\0\u1afd\0\u1b2c\0\u1b5b"+
    "\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17\0\u1c46\0\u1c75\0\u1ca4\0\u1cd3"+
    "\0\u1d02\0\u1d31\0\u1d60\0\u1d8f\0\u1dbe\0\u1ded\0\u1e1c\0\u1e4b"+
    "\0\u1e7a\0\u1ea9\0\274\0\u1ed8\0\u1f07\0\u1f36\0\u1f65\0\274"+
    "\0\u1f94\0\u1fc3\0\u1ff2\0\u2021\0\274\0\u2050\0\u207f\0\u20ae"+
    "\0\u20dd\0\u210c\0\u213b\0\u216a\0\u2199\0\u21c8\0\u21f7\0\u2226"+
    "\0\u2255\0\u2284\0\u22b3\0\u22e2\0\u2311\0\u2340\0\u236f\0\u239e"+
    "\0\274\0\u23cd\0\u23fc\0\274\0\u242b\0\274\0\u245a\0\u2489"+
    "\0\u24b8\0\u24e7\0\u2516\0\274\0\u2545\0\274\0\274\0\u2574"+
    "\0\274\0\u25a3\0\u25d2\0\274\0\274\0\u2601\0\274\0\u2630"+
    "\0\274\0\u265f\0\274\0\u268e\0\u26bd\0\u26ec\0\u271b\0\274"+
    "\0\u274a\0\u2779\0\274\0\u27a8\0\u27d7\0\u2806\0\u2835\0\u2864"+
    "\0\u2893\0\274\0\274\0\u28c2\0\274\0\u28f1\0\u2920\0\u294f"+
    "\0\u297e\0\u29ad\0\u29dc\0\u2a0b\0\u2a3a\0\274\0\274\0\u2a69"+
    "\0\274\0\u2a98\0\u2ac7\0\u2af6\0\u2b25\0\u2b54\0\274\0\u2b83"+
    "\0\u2bb2\0\u2be1\0\274\0\u2c10\0\u2c3f\0\u2c6e\0\u2c9d\0\274"+
    "\0\u2ccc\0\274\0\274\0\u2cfb\0\u2d2a\0\274\0\u2d59\0\u2d88"+
    "\0\u2db7\0\274\0\274\0\u2de6\0\274\0\u2e15\0\u2e44\0\274"+
    "\0\u2e73\0\274\0\274\0\274\0\u2ea2\0\u2ed1\0\274\0\u2f00"+
    "\0\u2f2f\0\u2f5e\0\274\0\u2f8d\0\u2fbc\0\u2feb\0\u301a\0\274";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[320];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\0\1\6\1\7\1\10\1\11\1\5"+
    "\1\12\1\13\1\5\1\14\1\15\1\16\1\5\1\17"+
    "\2\5\1\20\1\21\1\22\2\5\1\23\1\24\2\5"+
    "\1\25\1\26\2\5\1\27\1\30\1\31\2\5\1\32"+
    "\1\33\1\5\1\34\4\5\1\35\1\36\6\37\1\40"+
    "\50\37\2\41\1\42\2\41\1\42\13\41\1\43\35\41"+
    "\53\4\1\44\3\4\60\0\2\6\1\0\1\6\60\0"+
    "\1\45\6\0\1\46\4\0\6\46\44\0\1\47\61\0"+
    "\1\50\51\0\1\51\1\0\1\15\55\0\1\52\1\53"+
    "\5\0\1\54\1\55\1\56\1\57\1\60\4\0\1\61"+
    "\1\62\1\0\1\63\2\0\1\64\1\65\47\0\1\66"+
    "\61\0\1\67\4\0\1\70\51\0\1\71\60\0\1\72"+
    "\54\0\1\73\51\0\1\74\63\0\1\75\63\0\1\76"+
    "\40\0\1\77\52\0\1\100\10\0\1\101\51\0\1\102"+
    "\61\0\1\103\53\0\1\104\30\0\6\37\1\0\50\37"+
    "\6\0\1\105\50\0\2\41\1\0\2\41\1\0\13\41"+
    "\1\0\35\41\52\0\1\106\12\0\1\107\65\0\1\110"+
    "\4\0\6\110\40\0\1\111\3\0\1\47\56\0\1\112"+
    "\65\0\1\113\1\114\1\115\5\0\1\116\1\117\1\0"+
    "\1\120\2\0\1\121\1\122\24\0\1\123\3\0\1\53"+
    "\63\0\1\124\14\0\1\125\56\0\1\126\60\0\1\127"+
    "\51\0\1\130\61\0\1\131\51\0\1\132\70\0\1\133"+
    "\52\0\1\134\44\0\1\135\14\0\1\136\35\0\1\137"+
    "\3\0\1\140\52\0\1\141\21\0\1\142\46\0\1\143"+
    "\63\0\1\144\60\0\1\145\1\146\40\0\1\147\71\0"+
    "\1\150\53\0\1\151\56\0\1\152\61\0\1\153\42\0"+
    "\1\154\67\0\1\155\70\0\1\156\47\0\1\157\47\0"+
    "\1\160\60\0\1\161\30\0\1\162\65\0\1\163\4\0"+
    "\6\163\44\0\1\164\100\0\1\165\60\0\1\166\51\0"+
    "\1\167\54\0\1\170\70\0\1\171\52\0\1\172\44\0"+
    "\1\173\14\0\1\174\35\0\1\175\3\0\1\176\45\0"+
    "\1\177\65\0\1\200\73\0\1\201\51\0\1\202\1\0"+
    "\1\203\57\0\1\204\45\0\1\205\66\0\1\206\56\0"+
    "\1\207\54\0\1\210\50\0\1\211\54\0\1\212\7\0"+
    "\1\213\72\0\1\214\31\0\1\215\102\0\1\216\33\0"+
    "\1\217\60\0\1\220\67\0\1\221\61\0\1\222\57\0"+
    "\1\223\36\0\1\224\61\0\1\225\62\0\1\226\52\0"+
    "\1\227\67\0\1\230\57\0\1\231\60\0\1\232\57\0"+
    "\1\233\56\0\1\234\47\0\1\235\37\0\1\236\4\0"+
    "\6\236\40\0\1\237\3\0\1\164\77\0\1\240\57\0"+
    "\1\241\45\0\1\242\66\0\1\243\54\0\1\244\50\0"+
    "\1\245\54\0\1\246\7\0\1\247\72\0\1\250\31\0"+
    "\1\251\102\0\1\252\20\0\1\253\3\0\1\177\74\0"+
    "\1\254\50\0\1\255\70\0\1\256\62\0\1\257\53\0"+
    "\1\260\53\0\1\261\64\0\1\262\41\0\1\263\73\0"+
    "\1\264\51\0\1\265\63\0\1\266\41\0\1\267\64\0"+
    "\1\270\56\0\1\271\65\0\1\272\46\0\1\273\64\0"+
    "\1\274\47\0\1\275\52\0\1\276\64\0\1\277\60\0"+
    "\1\300\71\0\1\301\41\0\1\302\76\0\1\303\34\0"+
    "\1\304\52\0\1\305\67\0\1\306\34\0\1\307\4\0"+
    "\6\307\44\0\1\310\104\0\1\311\53\0\1\312\53\0"+
    "\1\313\47\0\1\314\73\0\1\315\51\0\1\316\63\0"+
    "\1\317\41\0\1\320\64\0\1\321\56\0\1\322\65\0"+
    "\1\323\30\0\1\324\71\0\1\325\54\0\1\326\71\0"+
    "\1\327\43\0\1\330\47\0\1\331\65\0\1\332\34\0"+
    "\1\333\72\0\1\334\70\0\1\335\43\0\1\336\71\0"+
    "\1\337\50\0\1\340\60\0\1\341\56\0\1\342\34\0"+
    "\1\343\12\0\1\344\56\0\1\5\104\0\1\345\36\0"+
    "\1\346\57\0\1\347\67\0\1\350\45\0\1\351\72\0"+
    "\1\352\40\0\1\353\100\0\1\354\25\0\1\355\4\0"+
    "\6\355\37\0\1\355\4\0\1\310\67\0\1\356\50\0"+
    "\1\357\64\0\1\360\50\0\1\361\70\0\1\362\44\0"+
    "\1\363\70\0\1\364\50\0\1\365\60\0\1\366\56\0"+
    "\1\367\50\0\1\370\53\0\1\324\2\0\1\355\77\0"+
    "\1\371\56\0\1\372\34\0\1\373\75\0\1\374\56\0"+
    "\1\375\47\0\1\376\67\0\1\377\55\0\1\u0100\62\0"+
    "\1\u0101\33\0\1\u0102\55\0\1\u0103\101\0\1\u0104\42\0"+
    "\1\u0105\66\0\1\u0106\46\0\1\u0107\52\0\1\u0108\72\0"+
    "\1\u0109\56\0\1\u010a\60\0\1\u010b\55\0\1\u010c\62\0"+
    "\1\u010d\33\0\1\u010e\56\0\1\u010f\75\0\1\u0110\30\0"+
    "\1\u0111\110\0\1\u0112\56\0\1\u0113\35\0\1\u0114\70\0"+
    "\1\u0115\60\0\1\u0116\37\0\1\u0117\71\0\1\u0118\67\0"+
    "\1\u0119\54\0\1\u011a\51\0\1\u011b\65\0\1\u011c\56\0"+
    "\1\u011d\47\0\1\u011e\60\0\1\u011f\40\0\1\u0120\102\0"+
    "\1\u0121\32\0\1\u0122\56\0\1\u0123\73\0\1\u0124\47\0"+
    "\1\u0125\47\0\1\u0126\110\0\1\u0127\27\0\1\u0128\66\0"+
    "\1\u0129\44\0\1\u012a\56\0\1\u012b\64\0\1\u012c\50\0"+
    "\1\u012d\74\0\1\u012e\52\0\1\u012f\43\0\1\u0130\65\0"+
    "\1\u0131\64\0\1\u0132\51\0\1\u0133\47\0\1\u0134\63\0"+
    "\1\u0135\65\0\1\u0136\41\0\1\u0137\43\0\1\u0138\122\0"+
    "\1\u0139\32\0\1\u013a\51\0\1\u013b\76\0\1\u013c\53\0"+
    "\1\u013d\61\0\1\u013e\60\0\1\u013f\34\0\1\u0140\37\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12361];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\1\1\1\11\2\1\2\11\3\1\1\11"+
    "\15\1\2\11\3\1\1\11\1\1\1\11\3\0\1\11"+
    "\35\0\2\11\2\0\1\1\41\0\1\11\1\0\1\11"+
    "\3\0\1\11\35\0\1\11\6\0\2\11\42\0\1\11"+
    "\4\0\1\11\4\0\1\11\23\0\1\11\2\0\1\11"+
    "\1\0\1\11\5\0\1\11\1\0\2\11\1\0\1\11"+
    "\2\0\2\11\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\1\11\2\0\1\11\6\0\2\11\1\0\1\11"+
    "\10\0\2\11\1\0\1\11\5\0\1\11\3\0\1\11"+
    "\4\0\1\11\1\0\2\11\2\0\1\11\3\0\2\11"+
    "\1\0\1\11\2\0\1\11\1\0\3\11\2\0\1\11"+
    "\3\0\1\11\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[320];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public static ArrayList<String[]> errores = new ArrayList<>();

    /* Buffer para construir el valor de la cadena actual */
    private StringBuilder cadenaActual = new StringBuilder();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }

    /* Convierte el contenido de @[...] a Unicode */
    private String convertirEmoji(String contenido) {
        if (contenido.equals(":smile:"))   return "\uD83D\uDE00"; // 😀
        if (contenido.equals(":sad:"))     return "\uD83E\uDD72"; // 🥲
        if (contenido.equals(":serious:")) return "\uD83D\uDE10"; // 😐
        if (contenido.equals(":heart:"))   return "\u2764\uFE0F"; // ❤️
        if (contenido.equals(":star:"))    return "\u2B50";        // ⭐
        if (contenido.equals(":cat:")  ||
            contenido.equals(":^^:"))      return "\uD83D\uDE3A"; // 😺

        // :) :)) :)))))
        if (contenido.matches(":\\)+"))    return "\uD83D\uDE00";
        // :( :((
        if (contenido.matches(":\\(+"))    return "\uD83E\uDD72";
        // :| :||
        if (contenido.matches(":\\|+"))    return "\uD83D\uDE10";
        // <3, <<3, :<3, :<<<<33333:
        if (contenido.matches("<+3+"))     return "\u2764\uFE0F";
        if (contenido.matches(":<+3+:?")) return "\u2764\uFE0F";

        // :star:N: o :star:N
        java.util.regex.Matcher m = java.util.regex.Pattern
            .compile(":star:(\\d+):?").matcher(contenido);
        if (m.matches()) {
            int n = Math.min(Integer.parseInt(m.group(1)), 50);
            StringBuilder sb = new StringBuilder();
            for (int k = 0; k < n; k++) sb.append("\u2B50");
            return sb.toString();
        }

        return null; // no reconocido
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerPKM(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(symPKM.EOF);
            }  // fall though
            case 321: break;
            case META: {
              return symbol(symPKM.EOF);
            }  // fall though
            case 322: break;
            case CADENA_STATE: {
              yybegin(YYINITIAL);
                     return symbol(symPKM.CADENA, cadenaActual.toString());
            }  // fall though
            case 323: break;
            case EMOJI_STATE: {
              yybegin(YYINITIAL); return symbol(symPKM.EOF);
            }  // fall though
            case 324: break;
            default:
          { return new java_cup.runtime.Symbol(symPKM.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignorar */
            }
          // fall through
          case 61: break;
          case 2:
            { cadenaActual = new StringBuilder();
                     yybegin(CADENA_STATE);
            }
          // fall through
          case 62: break;
          case 3:
            { return symbol(symPKM.COMA);
            }
          // fall through
          case 63: break;
          case 4:
            { return symbol(symPKM.GUION);
            }
          // fall through
          case 64: break;
          case 5:
            { return symbol(symPKM.SLASH);
            }
          // fall through
          case 65: break;
          case 6:
            { return symbol(symPKM.NUMERO, Double.parseDouble(yytext()));
            }
          // fall through
          case 66: break;
          case 7:
            { return symbol(symPKM.GT);
            }
          // fall through
          case 67: break;
          case 8:
            { return symbol(symPKM.LLAVE_ABRE);
            }
          // fall through
          case 68: break;
          case 9:
            { return symbol(symPKM.LLAVE_CIERRA);
            }
          // fall through
          case 69: break;
          case 10:
            { cadenaActual.append(yytext());
            }
          // fall through
          case 70: break;
          case 11:
            { yybegin(YYINITIAL);
                     return symbol(symPKM.CADENA, cadenaActual.toString());
            }
          // fall through
          case 71: break;
          case 12:
            { /* yytext() es el contenido + "]", quitamos el ] final */
                     String contenido = yytext();
                     contenido = contenido.substring(0, contenido.length() - 1);
                     String emoji = convertirEmoji(contenido);
                     if (emoji != null) {
                         cadenaActual.append(emoji);
                     } else {
                         /* No reconocido — agregar la notacion original */
                         cadenaActual.append("@[").append(contenido).append("]");
                     }
                     yybegin(CADENA_STATE);
            }
          // fall through
          case 72: break;
          case 13:
            { return symbol(symPKM.SLASH_GT);
            }
          // fall through
          case 73: break;
          case 14:
            { yybegin(EMOJI_STATE);
            }
          // fall through
          case 74: break;
          case 15:
            { yybegin(META);
            }
          // fall through
          case 75: break;
          case 16:
            { return symbol(symPKM.COLOR, "RED");
            }
          // fall through
          case 76: break;
          case 17:
            { return symbol(symPKM.COLOR, "SKY");
            }
          // fall through
          case 77: break;
          case 18:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 78: break;
          case 19:
            { return symbol(symPKM.COLOR, "BLUE");
            }
          // fall through
          case 79: break;
          case 20:
            { return symbol(symPKM.BORDER_TYPE, "LINE");
            }
          // fall through
          case 80: break;
          case 21:
            { return symbol(symPKM.FONT_VAL, "MONO");
            }
          // fall through
          case 81: break;
          case 22:
            { return symbol(symPKM.COLOR, "BLACK");
            }
          // fall through
          case 82: break;
          case 23:
            { return symbol(symPKM.COLOR, "GREEN");
            }
          // fall through
          case 83: break;
          case 24:
            { return symbol(symPKM.COLOR, "WHITE");
            }
          // fall through
          case 84: break;
          case 25:
            { return symbol(symPKM.TAG_DROP_OPEN);
            }
          // fall through
          case 85: break;
          case 26:
            { return symbol(symPKM.TAG_LINE_OPEN);
            }
          // fall through
          case 86: break;
          case 27:
            { return symbol(symPKM.TAG_OPEN_OPEN);
            }
          // fall through
          case 87: break;
          case 28:
            { return symbol(symPKM.TAG_TEXT_OPEN);
            }
          // fall through
          case 88: break;
          case 29:
            { return symbol(symPKM.BORDER_TYPE, "DOTTED");
            }
          // fall through
          case 89: break;
          case 30:
            { return symbol(symPKM.BORDER_TYPE, "DOUBLE");
            }
          // fall through
          case 90: break;
          case 31:
            { return symbol(symPKM.COLOR, "PURPLE");
            }
          // fall through
          case 91: break;
          case 32:
            { return symbol(symPKM.COLOR, "YELLOW");
            }
          // fall through
          case 92: break;
          case 33:
            { return symbol(symPKM.COLOR, yytext());
            }
          // fall through
          case 93: break;
          case 34:
            { return symbol(symPKM.TAG_DROP_CLOSE);
            }
          // fall through
          case 94: break;
          case 35:
            { return symbol(symPKM.TAG_LINE_CLOSE);
            }
          // fall through
          case 95: break;
          case 36:
            { return symbol(symPKM.TAG_OPEN_CLOSE);
            }
          // fall through
          case 96: break;
          case 37:
            { return symbol(symPKM.TAG_TEXT_CLOSE);
            }
          // fall through
          case 97: break;
          case 38:
            { return symbol(symPKM.STYLE_COLOR);
            }
          // fall through
          case 98: break;
          case 39:
            { return symbol(symPKM.TAG_STYLE_OPEN);
            }
          // fall through
          case 99: break;
          case 40:
            { return symbol(symPKM.TAG_TABLE_OPEN);
            }
          // fall through
          case 100: break;
          case 41:
            { return symbol(symPKM.FONT_VAL, "CURSIVE");
            }
          // fall through
          case 101: break;
          case 42:
            { return symbol(symPKM.TAG_STYLE_CLOSE);
            }
          // fall through
          case 102: break;
          case 43:
            { return symbol(symPKM.TAG_TABLE_CLOSE);
            }
          // fall through
          case 103: break;
          case 44:
            { return symbol(symPKM.STYLE_BORDER);
            }
          // fall through
          case 104: break;
          case 45:
            { return symbol(symPKM.TAG_SELECT_OPEN);
            }
          // fall through
          case 105: break;
          case 46:
            { return symbol(symPKM.ORIENTATION, "VERTICAL");
            }
          // fall through
          case 106: break;
          case 47:
            { return symbol(symPKM.TAG_SELECT_CLOSE);
            }
          // fall through
          case 107: break;
          case 48:
            { return symbol(symPKM.TAG_CONTENT_OPEN);
            }
          // fall through
          case 108: break;
          case 49:
            { return symbol(symPKM.TAG_ELEMENT_OPEN);
            }
          // fall through
          case 109: break;
          case 50:
            { return symbol(symPKM.TAG_SECTION_OPEN);
            }
          // fall through
          case 110: break;
          case 51:
            { return symbol(symPKM.TAG_CONTENT_CLOSE);
            }
          // fall through
          case 111: break;
          case 52:
            { return symbol(symPKM.TAG_ELEMENT_CLOSE);
            }
          // fall through
          case 112: break;
          case 53:
            { return symbol(symPKM.TAG_SECTION_CLOSE);
            }
          // fall through
          case 113: break;
          case 54:
            { return symbol(symPKM.TAG_MULTIPLE_OPEN);
            }
          // fall through
          case 114: break;
          case 55:
            { return symbol(symPKM.ORIENTATION, "HORIZONTAL");
            }
          // fall through
          case 115: break;
          case 56:
            { return symbol(symPKM.FONT_VAL, "SANS_SERIF");
            }
          // fall through
          case 116: break;
          case 57:
            { return symbol(symPKM.TAG_MULTIPLE_CLOSE);
            }
          // fall through
          case 117: break;
          case 58:
            { return symbol(symPKM.STYLE_SIZE);
            }
          // fall through
          case 118: break;
          case 59:
            { return symbol(symPKM.STYLE_FONT);
            }
          // fall through
          case 119: break;
          case 60:
            { return symbol(symPKM.STYLE_BG);
            }
          // fall through
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
