
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.example.pkmforms.analyzer.pkm;

/** CUP generated class containing symbol constants. */
public class symPKM {
  /* terminals */
  public static final int SLASH_GT = 37;
  public static final int TAG_MULTIPLE_CLOSE = 13;
  public static final int NUMERO = 33;
  public static final int STYLE_FONT = 26;
  public static final int TAG_CONTENT_CLOSE = 19;
  public static final int TAG_TABLE_CLOSE = 5;
  public static final int SLASH = 36;
  public static final int TAG_ELEMENT_OPEN = 22;
  public static final int TAG_STYLE_OPEN = 16;
  public static final int TAG_CONTENT_OPEN = 18;
  public static final int ORIENTATION = 31;
  public static final int TAG_TEXT_OPEN = 14;
  public static final int TAG_SELECT_CLOSE = 11;
  public static final int STYLE_SIZE = 27;
  public static final int BORDER_TYPE = 30;
  public static final int TAG_DROP_OPEN = 8;
  public static final int TAG_LINE_OPEN = 20;
  public static final int TAG_SECTION_OPEN = 2;
  public static final int GUION = 39;
  public static final int STYLE_COLOR = 24;
  public static final int TAG_STYLE_CLOSE = 17;
  public static final int TAG_TEXT_CLOSE = 15;
  public static final int TAG_SELECT_OPEN = 10;
  public static final int TAG_ELEMENT_CLOSE = 23;
  public static final int EOF = 0;
  public static final int TAG_TABLE_OPEN = 4;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int CADENA = 34;
  public static final int TAG_OPEN_CLOSE = 7;
  public static final int LLAVE_ABRE = 40;
  public static final int TAG_LINE_CLOSE = 21;
  public static final int COLOR = 32;
  public static final int STYLE_BORDER = 28;
  public static final int TAG_MULTIPLE_OPEN = 12;
  public static final int TAG_OPEN_OPEN = 6;
  public static final int TAG_SECTION_CLOSE = 3;
  public static final int LLAVE_CIERRA = 41;
  public static final int STYLE_BG = 25;
  public static final int GT = 38;
  public static final int TAG_DROP_CLOSE = 9;
  public static final int FONT_VAL = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TAG_SECTION_OPEN",
  "TAG_SECTION_CLOSE",
  "TAG_TABLE_OPEN",
  "TAG_TABLE_CLOSE",
  "TAG_OPEN_OPEN",
  "TAG_OPEN_CLOSE",
  "TAG_DROP_OPEN",
  "TAG_DROP_CLOSE",
  "TAG_SELECT_OPEN",
  "TAG_SELECT_CLOSE",
  "TAG_MULTIPLE_OPEN",
  "TAG_MULTIPLE_CLOSE",
  "TAG_TEXT_OPEN",
  "TAG_TEXT_CLOSE",
  "TAG_STYLE_OPEN",
  "TAG_STYLE_CLOSE",
  "TAG_CONTENT_OPEN",
  "TAG_CONTENT_CLOSE",
  "TAG_LINE_OPEN",
  "TAG_LINE_CLOSE",
  "TAG_ELEMENT_OPEN",
  "TAG_ELEMENT_CLOSE",
  "STYLE_COLOR",
  "STYLE_BG",
  "STYLE_FONT",
  "STYLE_SIZE",
  "STYLE_BORDER",
  "FONT_VAL",
  "BORDER_TYPE",
  "ORIENTATION",
  "COLOR",
  "NUMERO",
  "CADENA",
  "COMA",
  "SLASH",
  "SLASH_GT",
  "GT",
  "GUION",
  "LLAVE_ABRE",
  "LLAVE_CIERRA"
  };
}

